DATASET_PATH = './../dataset/'
OUT_PATH = './csv/'
MODEL_PATH = './classifier/model.hdf5'

WINDOW_LEN = 2
FREQUENCY = 22050
WINDOW_WIDTH = 44100
FRAME_WIDTH = 441
NUM_FRAMES_WINDOW = 100
ZCR_THRESHOLD = 0.2
